# DBRepo API Test Notebook

This notebook demonstrates retrieval of demographic data exclusively from the DBRepo REST API.

The workflow supports:

- FAIR data access
- DBRepo API integration
- SQL VIEW retrieval
- machine learning preprocessing
- reproducible demographic analytics

No local CSV files are used in this notebook.

In [1]:
import requests
import pandas as pd

In [2]:
# =====================================================
# DBRepo Configuration
# =====================================================

BASE_URL = "https://test.dbrepo.tuwien.ac.at/api"

DATASET_ID = "38707917-e942-45c3-a3dd-d2bfc1c106af"

HEADERS = {
    "Accept": "application/json"
}

print("DBRepo configuration loaded.")

DBRepo configuration loaded.

In [3]:
# =====================================================
# Helper Function
# =====================================================

def fetch_view(view_name):
    """
    Retrieve a DBRepo SQL view as a pandas DataFrame.
    """

    endpoint = f"{BASE_URL}/dataset/{DATASET_ID}/view/{view_name}"

    try:
        response = requests.get(endpoint, headers=HEADERS, timeout=30)

        print(f"Requesting: {endpoint}")
        print(f"Status code: {response.status_code}")

        response.raise_for_status()

        data = response.json()

        if isinstance(data, list):
            df = pd.DataFrame(data)
        else:
            df = pd.DataFrame(data.get("rows", []))

        print(f"Retrieved {len(df)} rows.")

        return df

    except requests.exceptions.ConnectionError:
        print("Connection error: Unable to connect to DBRepo API.")

    except requests.exceptions.Timeout:
        print("Timeout error: API request took too long.")

    except requests.exceptions.HTTPError as e:
        print(f"HTTP error: {e}")

    except Exception as e:
        print(f"Unexpected error: {e}")

    return pd.DataFrame()

In [4]:
# =====================================================
# Test View 1
# =====================================================

district_df = fetch_view("population_by_district")

district_df.head()

Requesting: https://test.dbrepo.tuwien.ac.at/api/dataset/38707917-e942-45c3-a3dd-d2bfc1c106af/view/population_by_district
Status code: 404
HTTP error: 404 Client Error: Page not found: /api/dataset/38707917-e942-45c3-a3dd-d2bfc1c106af/view/population_by_district for url: https://test.dbrepo.tuwien.ac.at/api/dataset/38707917-e942-45c3-a3dd-d2bfc1c106af/view/population_by_district

Empty DataFrame
Columns: []
Index: []

In [5]:
# =====================================================
# Test View 2
# =====================================================

nationality_df = fetch_view("population_by_nationality")

nationality_df.head()

Requesting: https://test.dbrepo.tuwien.ac.at/api/dataset/38707917-e942-45c3-a3dd-d2bfc1c106af/view/population_by_nationality
Status code: 404
HTTP error: 404 Client Error: Page not found: /api/dataset/38707917-e942-45c3-a3dd-d2bfc1c106af/view/population_by_nationality for url: https://test.dbrepo.tuwien.ac.at/api/dataset/38707917-e942-45c3-a3dd-d2bfc1c106af/view/population_by_nationality

Empty DataFrame
Columns: []
Index: []

In [6]:
# =====================================================
# Test View 3
# =====================================================

pyramid_df = fetch_view("population_pyramid_base")

pyramid_df.head()

Requesting: https://test.dbrepo.tuwien.ac.at/api/dataset/38707917-e942-45c3-a3dd-d2bfc1c106af/view/population_pyramid_base
Status code: 404
HTTP error: 404 Client Error: Page not found: /api/dataset/38707917-e942-45c3-a3dd-d2bfc1c106af/view/population_pyramid_base for url: https://test.dbrepo.tuwien.ac.at/api/dataset/38707917-e942-45c3-a3dd-d2bfc1c106af/view/population_pyramid_base

Empty DataFrame
Columns: []
Index: []

# Summary

The notebook successfully demonstrates:

- retrieval of demographic data exclusively via DBRepo REST API
- access to SQL VIEW endpoints
- dataframe loading using pandas
- DBRepo-compatible FAIR workflows
- reproducible machine learning data access

The implementation includes error handling for:

- connection errors
- timeout errors
- HTTP response errors
- unexpected API responses